log_format xhttp_log_format '$remote_addr - $remote_user [$time_local] '
                '"$request_method $uri $server_protocol" '
                '$status $body_bytes_sent '
                '"$http_referer" "$http_user_agent" [XHTTP]';

log_format https_log_format '$remote_addr - $remote_user [$time_local] '
                '"$request_method $uri $server_protocol" '
                '$status $body_bytes_sent '
                '"$http_referer" "$http_user_agent" [HTTPS]';

log_format stub_log_format '$remote_addr - $remote_user [$time_local] '
                '"$request_method $uri $server_protocol" '
                '$status $body_bytes_sent '
                '"$http_referer" "$http_user_agent" [STUB]';

# stub for invalid requests
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

    access_log /var/log/nginx/access.log stub_log_format;

	location / {
		return 444;
	}
}

# listen reality dest, show self-hosted example.com
server {
    listen unix:/dev/shm/xray_nginx_https.sock ssl proxy_protocol;
    set_real_ip_from unix:;
    real_ip_header proxy_protocol;

    server_name example.com;

    access_log /var/log/nginx/access.log https_log_format;

    location / {
        root /var/www/example.com/html;
        index index.html;
	    try_files $uri $uri/ =404;
    }

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# listen reality fallback, proxy to xhttp
server {
    listen unix:/dev/shm/xray_nginx_xhttp.sock proxy_protocol;
    set_real_ip_from unix:;
    real_ip_header proxy_protocol;
    
    http2 on;
  
    client_header_timeout 5m;
    keepalive_timeout 5m;

    access_log /var/log/nginx/access.log xhttp_log_format;
    
    location /your_xhttp_path {
        client_max_body_size 0;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_body_timeout 5m;
        grpc_read_timeout 315;
        grpc_send_timeout 5m;
        grpc_pass unix:/dev/shm/xray_xhttp.sock;
    }
}

# redirect http -> https
server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80 ;
    listen [::]:80 ;
    server_name example.com;
    return 404; # managed by Certbot
}